# Uses Github Action cpp-linter-action.
# https://cpp-linter.github.io/cpp-linter-action/

name: Clang Tidy
on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  clang-tidy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: CMake
      run: |
        set -ex;
        cmake -S . -B build \
          -DCMAKE_CXX_FLAGS="" \
          -DCMAKE_CXX_COMPILER="clang++" \
          -DCMAKE_C_COMPILER="clang" \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=on \
          -DCMAKE_BUILD_TYPE="Debug";

    - uses: emmett2020/cpp-linter@v0.0.54
      id: cpp-lint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         log-level: trace
         target-revision: refs/remotes/origin/main

