name: Code Coverage On Ubuntu 22.04
on:
  push:
    branches: [main, master]

jobs:
  code-coverage:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup C/C++ Compiler
      run: |
        echo "CC=gcc-11" >> ${GITHUB_ENV}
        echo "CXX=g++-11" >> ${GITHUB_ENV}

    - name: Install Dependencies
      run: |
        sudo apt install ninja-build;
        sudo apt install gcovr;

    - name: CMake
      run: |
        set -ex;
        cmake -S . -B build -GNinja \
          -DCMAKE_CXX_FLAGS="" \
          -DENABLE_COVERAGE=On \
          -DCMAKE_BUILD_TYPE="Debug";

    - name: Compile
      run: cmake --build build -v

    - name: Run Unittests
      run: ./build/main;

    - name: Collection result
      run: gcovr --html -o coverage.html

    - name: Upload Coverage Report to codecov.io
      uses: codecov/codecov-action@v4
      with:
        file: coverage.html
        token: ${{ secrets.CODECOV_TOKEN }} # required
        verbose: true
