name: Github Actions Pull Request
run-name: test_pull_request
on:
  pull_request:
    types:
      [opened, synchronize, reopened, assigned]
jobs:
  Examples:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test Example"
      - run: echo "${GITHUB_SHA} -- ${GITHUB_REF}"

