name: GITHUB ACTIONS STATUS
run-names: run-status
on: status
jobs:
  status_error_or_if:
    runs-on: ubunut-latest
    # if: >-
    #   github.event.state == 'error' ||
    #   github.event.state == 'fail'
    steps:
      - env: 
        DESCRIPTION: ${{ github.event.description }}
        name: "Test Status"
        run: |
          echo The status is error or failed: $DESCRIPTION

          

