name: Github Actions Demo
run-name: xxxxx-yyyy
on:
  pull_request:
    types:
      [opened, synchronize, reopened, assigned]
jobs:
  Examples:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test Example"
      - run: echo "${GITHUB_SHA} -- ${GITHUB_REF}"
      - run: exit -1

